---
# This example playbook will make snapshots of all the VMs that are included in the 'ansible_limit'
#
# The way this playbook is constructed allows for easy integration with existing playbooks,
# the task below is the only one required to make this role do it's work.
- hosts: all
  gather_facts: no
  tasks:
    - import_role:
        name: vmware
      vars:
        target_action: snap
        target_group: "{{ ansible_limit }}"
        target_state: present
        target_snapshot_name: ansible_snap_stuff # Remove this value to generate snapshot names with the current date
      run_once: yes
