---
- name: 'Initialize Docker Swarm'
  docker_swarm:
    state: 'present'

- name: 'Inspect swarm'
  docker_swarm:
    state: 'inspect'
  register: 'swarm_info'

- name: 'Join workers to Swarm'
  docker_swarm:
    state: 'join'
    remote_addrs:
      - "{{ ansible_facts['default_ipv4']['address'] }}"
    join_token: "{{ swarm_info['swarm_facts']['JoinTokens']['Worker'] }}"
    advertise_addr: "{{ ansible_facts['default_ipv4']['address'] }}"
  delegate_to: "{{ worker }}"
  loop: "{{ query('inventory_hostnames', 'workers') }}"
  loop_control:
    loop_var: 'worker'
