---
- name: 'Set up Docker Swarm'
  include_tasks: 'docker_swarm.yml'
  delegate_to: "{{ item }}"
  loop: "{{ groups.master }}"

- name: "Deploy containers"
  include_tasks: "{{ container }}.yml"
  loop: "{{ containers }}"
  loop_control:
    loop_var: 'container'

