---
- name: 'Create network'
  docker_network:
    name: 'mariadb_network'
    driver: 'overlay'

- name: 'Create directory for container data'
  file:
    path: "{{ gluster_mount_dir }}/mariadb_data"
    state: 'directory'

- name: 'Deploy MariaDB'
  docker_swarm_service:
    name: 'mariadb'
    image: 'mariadb'
    env:
      - "MYSQL_ROOT_PASSWORD={{ mariadb_root_password }}"
    mounts:
      - source: "{{ gluster_mount_dir }}/mariadb_data"
        target: '/var/lib/mysql'
        type: 'bind'
    networks:
      - 'mariadb_network'
    mode: 'replicated'
    replicas: 1
    restart_policy: 'any'
    user: null
