---
# This role will manage snapshots of all targeted VMs.
#
- name: Set snapshot name
  block:
  - setup:
      filter: ansible_date_time
  - set_fact:
      snapshot_name: "ansible_snap_{{ ansible_date_time.date }}"
  when: target_action == "present"

- name: Execute snapshot action
  vmware_guest_snapshot:
    hostname: "{{ hostvars[item.item]['vsphere_host'] }}"
    username: "{{ hostvars[item.item]['vsphere_username'] }}"
    password: "{{ hostvars[item.item]['vsphere_password'] }}"
    datacenter: "{{ item.folders[0].split('/')[1] }}"
    folder: "{{ item.folders[0] }}"
    name: "{{ item.item }}"
    validate_certs: "{{ vsphere_validate_certs }}"
    state: "{{ target_state }}"
    snapshot_name: "{{ snapshot_name.user_input | default( snapshot_name ) }}"
  delegate_to: "{{ hostvars[item.item]['vpshere_api_host'] }}"
  with_items: "{{ vm_location['results'] }}"
