---
# This playbook will manage the powerstate of all targeted VMs
#
- name: Set VM powerstate
  vmware_guest_powerstate:
    hostname: "{{ hostvars[item.item]['vsphere_host'] }}"
    username: "{{ hostvars[item.item]['vsphere_username'] }}"
    password: "{{ hostvars[item.item]['vsphere_password'] }}"
    folder: "{{ item.folders[0] }}"
    name: "{{ item.item }}"
    validate_certs: "{{ vsphere_validate_certs }}"
    state: "{{ target_state }}"
    state_change_timeout: "{{ vmware_powerstate_wait }}"
  delegate_to: "{{ hostvars[item.item]['vpshere_api_host'] }}"
  with_items: "{{ vm_location['results'] }}"
