---
galaxy_info:
  author: Jeffrey van Pelt
  description: Active Directory join for up to 2 domains
  company:

  license: GPLv3

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    - activedirectory
    - authentication
    - AD

dependencies: []
